// ══════════════════════════════════
// Extracted constants & translations
// ══════════════════════════════════

export const U_JELLY = '������';
export const U_WAVE = '������';

export const FREE_SEANCE_INDEX = 0;

export const ZONE_TO_PILIER = { 0: 'p2', 1: 'p1', 2: 'p3', 3: 'p4', 4: 'p5', 5: 'p6', 6: 'p8' };

export const T = {
  fr: {
    lang: 'fr', flag: '🇫🇷', nom: 'Français',
    tabs: ['FluidBody+', 'Résumé', 'Biblio', 'Profil'],
    cest_parti: "C'est parti !",
    resume_title: 'Résumé', resume_activite: 'Activité', resume_bouger: 'Bouger', resume_exercice: 'Exercice', resume_debout: 'Debout', resume_seances: 'Séances FluidBody', resume_no_seance: 'Aucune séance complétée', resume_progression: 'Progression', resume_global: 'Global', resume_streak: 'Streak',
    bonjour: (p) => p ? `Bonjour ${p}` : '',
    bonjour_mot: 'Bonjour',
    ob_tag: 'Une nouvelle façon d\'habiter son corps',
    ob_l1: 'Les autres apps te montrent ',
    ob_l1b: 'quoi faire.',
    ob_l2: 'FluidBody te montre ',
    ob_l2b: 'comment te préparer.',
    ob_sub: 'Parce qu\'un corps qui se comprend peut vraiment changer.',
    ob_cta: 'Commencer →',
    ob_compte: 'J\'ai déjà un compte',
    ob_bilan: 'Bilan corporel',
    ob_tensions: 'Où ressens-tu\ndes tensions ?',
    ob_select: 'Sélectionne une ou plusieurs zones',
    ob_zones: ['Dos / Nuque', 'Épaules', 'Hanches', 'Posture', 'Respiration', 'Stress', 'Bureau / Sédentaire'],
    ob_continuer: 'Continuer →',
    ob_explorer: 'Je veux tout explorer',
    ob_rythme_tag: 'Ton rythme',
    ob_rythme: 'Combien de temps\nas-tu chaque jour ?',
    ob_temps: ['5–10 min', '15–20 min', '30 min', '45 min +'],
    ob_varie: 'Ça varie',
    ob_prenom_tag: 'Dernière étape',
    ob_prenom: 'Comment\nt\'appelles-tu ?',
    ob_prenom_sub: 'Ton programme s\'adapte à ton profil.\nFluidBody t\'accompagne au quotidien.',
    ob_placeholder: 'Ton prénom...',
    ob_demarrer: 'Démarrer →',
    ob_anon: 'Entrer anonymement',
    ob_auth_tag: 'Compte FluidBody',
    ob_auth_title: 'Sauvegarde du profil',
    ob_auth_signup_title: 'Inscription',
    ob_auth_signin_title: 'Connexion',
    ob_auth_sub: 'Email et mot de passe pour synchroniser ta progression dans le cloud.',
    ob_auth_sub_signin: 'Entre tes identifiants pour retrouver ta progression.',
    ob_email_ph: 'ton@email.com',
    ob_pass_ph: 'Mot de passe (6 car. min.)',
    ob_auth_submit_up: 'Créer mon compte',
    ob_auth_submit_in: 'Me connecter',
    ob_auth_toggle_in: 'J\'ai déjà un compte →',
    ob_auth_toggle_up: 'Pas de compte ? S\'inscrire',
    ob_auth_skip: 'Continuer sans compte nuage →',
    ob_auth_err_short: 'Mot de passe : au moins 6 caractères.',
    ob_auth_err_email: 'Entre une adresse email valide.',
    ob_auth_confirm: 'Si une confirmation est demandée, vérifie ta boîte mail puis reconnecte-toi.',
    ob_auth_err_net: 'Erreur réseau.',
    ob_auth_no_cloud: 'Sauvegarde cloud indisponible sur cet environnement. Tes identifiants ne seront pas enregistrés sur un serveur.',
    ob_auth_continue_local: 'Continuer en local →',
    piliers: ['Épaules', 'Dos', 'Mobilité', 'Posture', 'Eldoa', 'Golf', 'Mat Pilates', 'Office'],
    etapes: { Comprendre: 'Comprendre', Ressentir: 'Ressentir', Préparer: 'Préparer', Exécuter: 'Exécuter', Évoluer: 'Évoluer' },
    retour: '← Mon Corps',
    seances_done: (n) => `${n} / 20 séances complétées`,
    m_seances: 'Séances', m_streak: 'Streak', m_progress: 'Progression',
    retour_video: '← Retour',
    video_resume: (t) => `Reprise · ${t}`,
    reprise_badge: 'Reprise',
    video_load_error: `La vidéo n'a pas pu être chargée.`,
    video_retry: 'Réessayer',
    seance_done: '✓  Séance terminée',
    biblio_titre: 'Bibliothèque',
    biblio_sub: 'Comprendre pour mieux ressentir',
    tab_piliers: 'Les 6 piliers',
    tab_methode: 'La méthode',
    tab_pour_vous: 'Pour vous',
    tab_explorer: 'Explorer',
    tab_programmes: 'Programmes',
    tab_recherche: '\uD83D\uDD0D',
    search_placeholder: 'Chercher une séance...',
    search_no_results: 'Aucun résultat',
    explore_free_title: 'Sélection gratuite du mois',
    explore_free_sub: 'Essayez cette séance une fois, sans abonnement requis',
    explore_new: 'Nouvelles sélections pour vous',
    prog_section_title: 'Vos programmes sur mesure',
    prog_section_sub: 'Programmes prédéfinis pour continuer sur votre lancée ou intensifier votre routine.',
    prog_debuter: 'Débuter',
    prog_debuter_sub: 'Épaules, Dos et Mobilité',
    prog_debuter_duree: '3 JOURS · 10 MIN/JOUR',
    prog_apercu: 'Aperçu du programme',
    prog_custom_title: 'Créez votre propre programme',
    prog_custom_sub: 'Choisissez les activités et définissez votre programme.',
    prog_custom_card: 'Programme personnalisé',
    prog_custom_card_sub: 'Vos activités, la durée de vos exercices, vos jours et votre rythme.',
    prog_custom_btn: 'Créer un programme',
    prog_create_title: 'Créer un programme',
    prog_select_piliers: 'Sélectionne tes piliers',
    prog_duree_label: 'Durée par séance',
    prog_jours_label: 'Jours par semaine',
    prog_save: 'Enregistrer',
    prog_saved: 'Programme enregistré !',
    prog_mes_programmes: 'Mes programmes',
    prog_thematiques_title: 'Programmes thématiques',
    prog_thematiques_sub: 'Des parcours ciblés pour tes objectifs',
    prog_reveil: 'Réveil Matinal',
    prog_reveil_sub: 'Réveille ton corps en douceur chaque matin',
    prog_dos: 'Mal de dos',
    prog_dos_sub: 'Soulage et renforce ton dos en 21 jours',
    prog_posttravail: 'Post-travail',
    prog_posttravail_sub: 'Décompresse après une journée assise',
    prog_core: 'Core & Plancher',
    prog_core_sub: 'Renforce ton centre et ta stabilité',
    prog_souplesse: 'Souplesse totale',
    prog_souplesse_sub: 'Gagne en mobilité sur tout le corps',
    prog_notif_days: 'Jours de rappel', prog_notif_hour: 'Heure de rappel', prog_notif_body: "C'est l'heure de ta séance",
    partage_title: 'Partage', partage_progression: 'Partager ma progression', partage_btn: 'Partager', partage_share_msg: 'Ma progression FluidBody+ Pilates', partage_inviter: 'Inviter des amis', partage_invite_btn: 'Inviter par SMS / Email', partage_invite_msg: 'Rejoins-moi sur FluidBody+ Pilates !', partage_en_attente: 'En attente', partage_invitation: 'Invitation', partage_defis: 'Défis', partage_creer_defi: 'Créer un défi', partage_choisir_pilier: 'Choisis un pilier', partage_duree_defi: 'Durée', partage_lancer: 'Lancer',
    profil_donnees_title: 'Confidentialité', profil_donnees_desc: 'Découvrez comment sont gérées vos données. Vos données restent sur votre appareil. Aucune donnée personnelle n\'est envoyée à des serveurs tiers. Les séances, la progression et les préférences sont stockées localement. Si vous vous connectez, seul votre email est synchronisé pour sauvegarder votre profil.', profil_donnees_local: 'Données stockées localement sur votre appareil', profil_donnees_no_tracking: 'Aucun tracking publicitaire', profil_donnees_healthkit: 'HealthKit : données lues uniquement, jamais partagées',
    biblio_intro: 'La méthode FluidBody repose sur 5 étapes progressives. Chaque séance les traverse dans l\'ordre.',
    lire: ' de lecture',
    retour_biblio: '← Bibliothèque',
    points_cles: 'Points clés',
    mon_parcours: 'Mon Parcours',
    prog_globale: 'Progression globale',
    par_pilier: 'Par pilier',
    parcours_langue: 'Langue',
    mon_compte: 'Mon compte',
    compte_info: [['Application', 'FluidBody · Pilates'], ['Version', 'FluidBody Beta 1.0'], ['Méthode', 'Pilates Conscient · 30 ans']],
    progresser_sub: (p) => `${p}% du parcours complété`,
    recommande_pour_toi: 'POUR TOI',
    seance_gratuite: 'Séance gratuite',
    seance_du_jour_sub: "Recommandée pour toi aujourd'hui",
    commencer_seance: 'Commencer →',
    deja_faite: "✓ Déjà faite aujourd'hui",
    notif_section: 'Rappels',
    notif_hour_label: 'Heure du rappel',
    notif_pause_label: 'Pauses actives au bureau',
    notif_pause_sub: '9h-17h en semaine',
    notif_title: `FluidBody ${U_JELLY}`,
    notif_body: "Ta séance démo t'attend. Ton corps a besoin de toi.",
    notif_pause_title: 'Pause Active 🪑', notif_pause_body: "C'est le moment de bouger ! 5 min d'étirements au bureau.",
    coach_title: 'Votre Coach', coach_name: 'Sabrina', coach_subtitle: 'Experte Pilates · 30 ans d\'expérience', coach_bio: 'Passionnée par le mouvement conscient, je vous guide vers un corps plus libre et plus fort.', coach_more: 'En savoir plus', coach_avec: 'Avec Sabrina', coach_exp: '30 ans d\'expérience', coach_quote: '"Je vous accompagne pas à pas vers un corps plus libre."',
    coach_full_bio: 'Sabrina Tissot est la fondatrice d\'Espace Pilates, le premier studio de Pilates de la Riviera suisse, à La Tour-de-Peilz.\n\nDiplômée de l\'École Polytechnique de Lausanne, elle se forme au Pilates auprès d\'Anna Maria Cova à Milan dès l\'an 2000, puis développe son expertise au Villagio Internazionale, grande institution européenne du bien-être.\n\nFormatrice internationale (Milan, New York, Paris), Sabrina est aussi la co-créatrice du Pilawalk™, un système de marche tonifiante, et l\'auteure d\'un protocole d\'évaluation physique et posturale pour golfeurs.\n\nSa philosophie : le mouvement est intimement lié à l\'art de vivre. Avec rigueur et empathie, elle guide chacun vers une meilleure compréhension de son corps — avec précision, sensibilité et joie de vivre.',
    dev_title: 'Développeur', dev_name: 'Yvan', dev_subtitle: 'Fondateur · Ingénieur & Spécialiste Pilates', dev_more: 'En savoir plus',
    dev_full_bio: 'Yvan Tissot, Fondateur\n\nAncien Hockeyeur de Ligue Nationale | Ingénieur en Informatique | Spécialiste Pilates et Pilawalk\n\nYvan a débuté comme hockeyeur dans la Ligue Nationale suisse, une expérience qui a forgé sa discipline et son esprit d\'équipe. Par la suite, il a exercé comme ingénieur en informatique avant de se consacrer, avec Sabrina, au bien-être de leur clientèle à travers le Pilates.\n\nEnsemble, ils ont développé le Pilawalk™, une méthode innovante de marche active qui associe l\'entraînement physique au plaisir de bouger.\n\nLeur approche personnalisée et bienveillante vise à accompagner chacun dans son parcours de santé et d\'équilibre, en mettant en avant des techniques qui renforcent aussi bien le corps que l\'esprit.',
    first_seance_title: 'Bravo !', first_seance_sub: 'Première séance terminée !\nCrée un compte gratuit pour sauvegarder ta progression et ne jamais la perdre.', first_seance_create: 'Créer mon compte', first_seance_later: 'Plus tard',
    milestone_5: 'Tu construis une habitude !', milestone_10: 'Ton corps se transforme !', milestone_15: 'Tu es sur la bonne voie !', milestone_20: 'Bravo, 20 séances !', milestone_25: 'Un quart du chemin !', milestone_30: 'Ta discipline est remarquable !', milestone_35: 'Presque au sommet !', milestone_40: 'Maîtrise totale !',
    save_progress_title: 'Sauvegarde ta progression', save_progress_sub: 'Crée un compte gratuit pour ne rien perdre',
    meduse_card_title: 'Ta méduse',
    calendar_title: 'Activité récente', recommended_next: 'Recommandée pour toi', weekly_goal: 'Objectif semaine', weekly_done: 'Objectif atteint ! 🎉', weekly_remaining: 'séance(s) restante(s)',
    body_map_title: 'Bilan corporel', streak_protect_title: 'Protège ton streak !', streak_protect_sub: 'Fais une micro-séance de 2 min pour ne pas perdre tes jours',
    pause_bureau_tag: 'Pause active', pause_bureau_title: '5 min au bureau', pause_bureau_sub: 'Étire-toi sans quitter ta chaise',
    meduse_name_btn: 'Donne-lui un nom', meduse_name_ph: 'Nom de ta méduse', meduse_rename: 'Renommer',
    auth_apple: 'Continuer avec Apple', auth_google: 'Continuer avec Google', auth_or: 'ou', auth_social_soon: 'Disponible dans la version App Store.',
    demo_limit: "Abonne-toi pour voir la suite",
    motivation: (streak) => streak === 0 ? '"Commence aujourd\'hui.\nTon corps t\'attend."' :
      streak < 3  ? `"${streak} jour${streak > 1 ? 's' : ''} de suite. Continue."` :
      streak < 7  ? `"${streak} jours consécutifs !\nTon corps s\'éveille."` :
      streak < 14 ? `"${streak} jours ! Une vraie habitude\nse construit."` :
      `"${streak} jours. Tu es remarquable. ${U_WAVE}"`,
    celebration: 'Ton corps a progressé.\nContinue comme ça \uD83D\uDCAA',
    biblio_signature: '— FluidBody',
    premium_alert_title: 'Contenu Premium',
    premium_alert_simulate: 'Voir les offres',
    premium_alert_later: 'Plus tard',
    paywall_title: 'Du Pilates pour tout le monde',
    paywall_sub: 'Des séances guidées par Sabrina, experte Pilates depuis 30 ans',
    paywall_badge: '7 JOURS GRATUITS',
    paywall_yearly_link: '99 CHF/an · Économisez 35%',
    paywall_monthly: 'Mensuel',
    paywall_yearly: 'Annuel',
    paywall_buy_monthly: 'Acheter mensuel',
    paywall_buy_yearly: 'Acheter annuel',
    paywall_restore: 'Restaurer mes achats',
    paywall_b1: '8 piliers, des séances guidées par Sabrina',
    paywall_b2: 'Nouvelles séances ajoutées régulièrement',
    paywall_b3: 'Reprise automatique de tes séances',
    paywall_b4: 'Suivi de progression & streak',
    paywall_b5: 'Compatible Apple Health',
    paywall_close: 'Fermer',
    paywall_prices_loading: 'Chargement des prix…',
    paywall_not_available: 'Achats indisponibles (Expo Go / simulateur).',
    paywall_start: 'Commencer — 7 jours gratuits · sans carte bleue',
    paywall_per_month: '/mois',
    paywall_price_detail: '12.90 CHF/mois après l\'essai gratuit',
    paywall_access: 'Accès immédiat à tous les piliers · Sans engagement',
    paywall_try_free: 'Essayer avec la séance gratuite',
    free_try_once: 'Essayez une fois cet épisode gratuitement',
    free_go: "C'est parti !",
    subscription_status_label: 'Abonnement FluidBody+',
    subscription_status_active: 'Actif — toutes les séances',
    subscription_status_free: 'Inactif',
    subscription_reset: 'Restaurer mes achats',
    weekly_summary: 'Cette semaine',
    weekly_sessions_label: 'Séances',
    weekly_minutes_label: 'Minutes',
    dl_title: 'Téléchargements',
    dl_download: 'Télécharger',
    dl_downloading: 'Téléchargement...',
    dl_downloaded: 'Hors ligne',
    dl_delete: 'Supprimer',
    dl_delete_all: 'Tout supprimer',
    dl_storage: 'Espace utilisé',
    dl_no_downloads: 'Aucun téléchargement',
    dl_error: 'Erreur de téléchargement',
    dl_confirm_delete: 'Supprimer ce téléchargement ?',
    dl_confirm_delete_all: 'Supprimer tous les téléchargements ?',
    live_title: 'Cours en direct',
    live_subtitle: 'Rejoins Sabrina en live chaque semaine',
    live_join: 'Rejoindre',
    live_today: "Aujourd'hui",
    live_with: 'avec',
    live_info_title: 'Comment ça marche ?',
    live_info_body: "Connecte-toi à l'heure du cours et clique sur \"Rejoindre\". Sabrina te guide en temps réel. Active les rappels pour ne rien manquer !",
    live_no_class: 'Pas de cours prévu',
    live_reminder_set: 'Rappel activé !',
  },
  en: {
    lang: 'en', flag: '🇬🇧', nom: 'English',
    tabs: ['FluidBody+', 'Summary', 'Library', 'Profile'],
    cest_parti: "Let's go!",
    resume_title: 'Summary', resume_activite: 'Activity', resume_bouger: 'Move', resume_exercice: 'Exercise', resume_debout: 'Stand', resume_seances: 'FluidBody Sessions', resume_no_seance: 'No sessions completed', resume_progression: 'Progress', resume_global: 'Overall', resume_streak: 'Streak',
    bonjour: (p) => p ? `Hello ${p}` : '',
    bonjour_mot: 'Hello',
    ob_tag: 'A new way to inhabit your body',
    ob_l1: 'Other apps show you ',
    ob_l1b: 'what to do.',
    ob_l2: 'FluidBody shows you ',
    ob_l2b: 'how to prepare.',
    ob_sub: 'Because a body that understands itself can truly change.',
    ob_cta: 'Get Started →',
    ob_compte: 'I already have an account',
    ob_bilan: 'Body assessment',
    ob_tensions: 'Where do you feel\ntension?',
    ob_select: 'Select one or more areas',
    ob_zones: ['Back / Neck', 'Shoulders', 'Hips', 'Posture', 'Breathing', 'Stress', 'Office / Sedentary'],
    ob_continuer: 'Continue →',
    ob_explorer: 'I want to explore everything',
    ob_rythme_tag: 'Your rhythm',
    ob_rythme: 'How much time do you\nhave each day?',
    ob_temps: ['5–10 min', '15–20 min', '30 min', '45 min +'],
    ob_varie: 'It varies',
    ob_prenom_tag: 'Last step',
    ob_prenom: 'What\'s\nyour name?',
    ob_prenom_sub: 'Your program adapts to your profile.\nFluidBody supports you every day.',
    ob_placeholder: 'Your first name...',
    ob_demarrer: 'Get started →',
    ob_anon: 'Enter anonymously',
    ob_auth_tag: 'FluidBody account',
    ob_auth_title: 'Save your profile',
    ob_auth_signup_title: 'Sign up',
    ob_auth_signin_title: 'Sign in',
    ob_auth_sub: 'Use email and password to sync your progress in the cloud.',
    ob_auth_sub_signin: 'Enter your credentials to restore your progress.',
    ob_email_ph: 'you@email.com',
    ob_pass_ph: 'Password (min. 6 characters)',
    ob_auth_submit_up: 'Create account',
    ob_auth_submit_in: 'Sign in',
    ob_auth_toggle_in: 'I already have an account →',
    ob_auth_toggle_up: 'No account? Sign up',
    ob_auth_skip: 'Continue without cloud account →',
    ob_auth_err_short: 'Password must be at least 6 characters.',
    ob_auth_err_email: 'Enter a valid email address.',
    ob_auth_confirm: 'If email confirmation is required, check your inbox then sign in.',
    ob_auth_err_net: 'Network error.',
    ob_auth_no_cloud: `Cloud backup isn't available in this build. Your credentials won't be saved to a server.`,
    ob_auth_continue_local: 'Continue locally →',
    piliers: ['Shoulders', 'Back', 'Mobility', 'Posture', 'Eldoa', 'Golf', 'Mat Pilates', 'Office'],
    etapes: { Comprendre: 'Understand', Ressentir: 'Feel', Préparer: 'Prepare', Exécuter: 'Execute', Évoluer: 'Evolve' },
    retour: '← My Body',
    seances_done: (n) => `${n} / 20 sessions completed`,
    m_seances: 'Sessions', m_streak: 'Streak', m_progress: 'Progress',
    retour_video: '← Back',
    video_resume: (t) => `Resumed · ${t}`,
    reprise_badge: 'Resume',
    video_load_error: `Couldn't load the video.`,
    video_retry: 'Try again',
    seance_done: '✓  Session complete',
    biblio_titre: 'Library',
    biblio_sub: 'Understand to feel better',
    tab_piliers: 'The 6 pillars',
    tab_methode: 'The method',
    tab_pour_vous: 'For You',
    tab_explorer: 'Explore',
    tab_programmes: 'Programs',
    tab_recherche: '\uD83D\uDD0D',
    search_placeholder: 'Search a session...',
    search_no_results: 'No results',
    explore_free_title: 'Free pick of the month',
    explore_free_sub: 'Try this session once, no subscription required',
    explore_new: 'New picks for you',
    prog_section_title: 'Your tailored programs',
    prog_section_sub: 'Pre-built programs to keep your momentum or intensify your routine.',
    prog_debuter: 'Get started',
    prog_debuter_sub: 'Shoulders, Back and Mobility',
    prog_debuter_duree: '3 DAYS · 10 MIN/DAY',
    prog_apercu: 'Program overview',
    prog_custom_title: 'Create your own program',
    prog_custom_sub: 'Choose activities and define your program.',
    prog_custom_card: 'Custom program',
    prog_custom_card_sub: 'Your activities, exercise duration, your days and your pace.',
    prog_custom_btn: 'Create a program',
    prog_create_title: 'Create a program',
    prog_select_piliers: 'Select your pillars',
    prog_duree_label: 'Duration per session',
    prog_jours_label: 'Days per week',
    prog_save: 'Save',
    prog_saved: 'Program saved!',
    prog_mes_programmes: 'My programs',
    prog_notif_days: 'Reminder days', prog_notif_hour: 'Reminder time', prog_notif_body: 'Time for your session',
    partage_title: 'Share', partage_progression: 'Share my progress', partage_btn: 'Share', partage_share_msg: 'My FluidBody+ Pilates progress', partage_inviter: 'Invite friends', partage_invite_btn: 'Invite via SMS / Email', partage_invite_msg: 'Join me on FluidBody+ Pilates!', partage_en_attente: 'Pending', partage_invitation: 'Invitation', partage_defis: 'Challenges', partage_creer_defi: 'Create a challenge', partage_choisir_pilier: 'Choose a pillar', partage_duree_defi: 'Duration', partage_lancer: 'Start',
    profil_donnees_title: 'Privacy', profil_donnees_desc: 'Learn how your data is managed. Your data stays on your device. No personal data is sent to third-party servers. Sessions, progress and preferences are stored locally. If you sign in, only your email is synced to save your profile.', profil_donnees_local: 'Data stored locally on your device', profil_donnees_no_tracking: 'No advertising tracking', profil_donnees_healthkit: 'HealthKit: data read only, never shared',
    biblio_intro: 'The FluidBody method is built on 5 progressive steps. Each session follows them in order.',
    lire: ' read',
    retour_biblio: '← Library',
    points_cles: 'Key points',
    mon_parcours: 'My Journey',
    prog_globale: 'Overall progress',
    par_pilier: 'By pillar',
    parcours_langue: 'Language',
    mon_compte: 'My account',
    compte_info: [['App', 'FluidBody · Pilates'], ['Version', 'FluidBody Beta 1.0'], ['Method', 'Conscious Pilates · 30 years']],
    progresser_sub: (p) => `${p}% of journey completed`,
    recommande_pour_toi: 'FOR YOU',
    seance_gratuite: 'Free session',
    seance_du_jour_sub: 'Recommended for you today',
    commencer_seance: 'Start →',
    deja_faite: '✓ Already done today',
    notif_section: 'Reminders',
    notif_hour_label: 'Reminder time',
    notif_pause_label: 'Active desk breaks',
    notif_pause_sub: '9AM-5PM weekdays',
    notif_title: `FluidBody ${U_JELLY}`,
    notif_body: 'Your demo session is waiting. Your body needs you.',
    notif_pause_title: 'Active Break 🪑', notif_pause_body: 'Time to move! 5 min desk stretches.',
    coach_title: 'Your Coach', coach_name: 'Sabrina', coach_subtitle: 'Pilates Expert · 30 years experience', coach_bio: 'Passionate about conscious movement, I guide you towards a freer, stronger body.', coach_more: 'Learn more', coach_avec: 'With Sabrina', coach_exp: '30 years experience', coach_quote: '"I guide you step by step towards a freer body."',
    coach_full_bio: 'Sabrina Tissot is the founder of Espace Pilates, the first Pilates studio on the Swiss Riviera, in La Tour-de-Peilz.\n\nA graduate of the École Polytechnique de Lausanne, she trained in Pilates with Anna Maria Cova in Milan in 2000, then honed her expertise at the Villagio Internazionale, a leading European wellness institution.\n\nAn international trainer (Milan, New York, Paris), Sabrina also co-created Pilawalk™, a toning walking system, and authored a physical and postural assessment protocol for golfers.\n\nHer philosophy: movement is intimately linked to the art of living. With rigour and empathy, she guides everyone towards a better understanding of their body — with precision, sensitivity and joie de vivre.',
    dev_title: 'Developer', dev_name: 'Yvan', dev_subtitle: 'Founder · Engineer & Pilates Specialist', dev_more: 'Learn more',
    dev_full_bio: 'Yvan Tissot, Founder\n\nFormer National League Hockey Player | Software Engineer | Pilates & Pilawalk Specialist\n\nYvan began his career as a hockey player in the Swiss National League, an experience that shaped his discipline and team spirit. He then worked as a software engineer before dedicating himself, alongside Sabrina, to their clients\' well-being through Pilates.\n\nTogether, they developed Pilawalk™, an innovative active walking method that combines physical training with the joy of movement.\n\nTheir personalised and caring approach aims to support everyone on their journey to health and balance, using techniques that strengthen both body and mind.',
    first_seance_title: 'Well done!', first_seance_sub: 'First session complete!\nCreate a free account to save your progress.', first_seance_create: 'Create my account', first_seance_later: 'Later',
    milestone_5: 'Building a habit!', milestone_10: 'Your body is transforming!', milestone_15: 'You are on the right track!', milestone_20: 'Bravo, 20 sessions!', milestone_25: 'A quarter of the way!', milestone_30: 'Your discipline is remarkable!', milestone_35: 'Almost at the top!', milestone_40: 'Total mastery!',
    save_progress_title: 'Save your progress', save_progress_sub: 'Create a free account to keep everything',
    meduse_card_title: 'Your jellyfish',
    calendar_title: 'Recent activity', recommended_next: 'Recommended for you', weekly_goal: 'Weekly goal', weekly_done: 'Goal reached! 🎉', weekly_remaining: 'session(s) remaining',
    body_map_title: 'Body assessment', streak_protect_title: 'Protect your streak!', streak_protect_sub: 'Do a 2-min micro-session to keep your days',
    pause_bureau_tag: 'Active break', pause_bureau_title: '5 min at your desk', pause_bureau_sub: 'Stretch without leaving your chair',
    meduse_name_btn: 'Give it a name', meduse_name_ph: 'Your jellyfish name', meduse_rename: 'Rename',
    auth_apple: 'Continue with Apple', auth_google: 'Continue with Google', auth_or: 'or', auth_social_soon: 'Available in the App Store version.',
    demo_limit: 'Subscribe to see the rest',
    motivation: (streak) => streak === 0 ? '"Start today.\nYour body is waiting."' :
      streak < 3  ? `"${streak} day${streak > 1 ? 's' : ''} in a row. Keep going."` :
      streak < 7  ? `"${streak} days in a row!\nYour body is awakening."` :
      streak < 14 ? `"${streak} days! A real habit\nis forming."` :
      `"${streak} days. You are remarkable. ${U_WAVE}"`,
    celebration: 'Your body has progressed.\nKeep it up \uD83D\uDCAA',
    biblio_signature: '— FluidBody',
    premium_alert_title: 'Premium content',
    premium_alert_simulate: 'See offers',
    premium_alert_later: 'Later',
    paywall_title: 'Pilates for everyone',
    paywall_sub: 'Sessions guided by Sabrina, Pilates expert for 30 years',
    paywall_badge: '7 DAYS FREE',
    paywall_yearly_link: '99 CHF/year · Save 35%',
    paywall_monthly: 'Monthly',
    paywall_yearly: 'Yearly',
    paywall_buy_monthly: 'Buy monthly',
    paywall_buy_yearly: 'Buy yearly',
    paywall_restore: 'Restore purchases',
    paywall_b1: '8 pillars, sessions guided by Sabrina',
    paywall_b2: 'New sessions added regularly',
    paywall_b3: 'Auto-resume your sessions',
    paywall_b4: 'Progress tracking & streak',
    paywall_b5: 'Apple Health compatible',
    paywall_close: 'Close',
    paywall_prices_loading: 'Loading prices…',
    paywall_not_available: 'Purchases unavailable (Expo Go / simulator).',
    paywall_start: 'Start — 7 days free · no credit card',
    paywall_per_month: '/month',
    paywall_price_detail: '12.90 CHF/month after free trial',
    paywall_access: 'Instant access to all pillars · No commitment',
    paywall_try_free: 'Try the free session',
    free_try_once: 'Try this episode once for free',
    free_go: "Let's go!",
    subscription_status_label: 'FluidBody+ Subscription',
    subscription_status_active: 'Active — all sessions',
    subscription_status_free: 'Inactive',
    subscription_reset: 'Restore purchases',
    weekly_summary: 'This week',
    weekly_sessions_label: 'Sessions',
    weekly_minutes_label: 'Minutes',
    dl_title: 'Downloads',
    dl_download: 'Download',
    dl_downloading: 'Downloading...',
    dl_downloaded: 'Offline',
    dl_delete: 'Delete',
    dl_delete_all: 'Delete all',
    dl_storage: 'Storage used',
    dl_no_downloads: 'No downloads',
    dl_error: 'Download error',
    dl_confirm_delete: 'Delete this download?',
    dl_confirm_delete_all: 'Delete all downloads?',
    live_title: 'Live Classes',
    live_subtitle: 'Join Sabrina live every week',
    live_join: 'Join',
    live_today: 'Today',
    live_with: 'with',
    live_info_title: 'How does it work?',
    live_info_body: 'Connect at class time and tap "Join". Sabrina guides you in real time. Enable reminders so you never miss a class!',
    live_no_class: 'No class scheduled',
    live_reminder_set: 'Reminder set!',
  },
};


export const SEANCES_FR = {
  p1: [['Comprendre l\'épaule', '12 min', 'Comprendre'], ['La coiffe des rotateurs', '15 min', 'Comprendre'], ['Ressentir les omoplates', '12 min', 'Ressentir'], ['Le poids du bras', '15 min', 'Ressentir'], ['Cercles de conscience', '18 min', 'Ressentir'], ['Libérer les trapèzes', '20 min', 'Préparer'], ['Mobiliser la scapula', '22 min', 'Préparer'], ['Activer le dentelé', '25 min', 'Préparer'], ['Ouverture thoracique', '28 min', 'Préparer'], ['Proprioception épaule', '30 min', 'Préparer'], ['Le geste juste', '25 min', 'Exécuter'], ['Élévation consciente', '28 min', 'Exécuter'], ['Rotation externe guidée', '30 min', 'Exécuter'], ['Tirés et poussés', '32 min', 'Exécuter'], ['Circuit épaule complète', '35 min', 'Exécuter'], ['Force & souplesse I', '35 min', 'Évoluer'], ['Épaule sous charge', '38 min', 'Évoluer'], ['Équilibre scapulaire', '40 min', 'Évoluer'], ['L\'épaule athlétique', '42 min', 'Évoluer'], ['Maîtrise totale', '45 min', 'Évoluer']],
  p2: [['Le dos expliqué', '12 min', 'Comprendre'], ['Pourquoi le dos souffre', '15 min', 'Comprendre'], ['La nuque et ses tensions', '15 min', 'Comprendre'], ['Ressentir sa colonne', '12 min', 'Ressentir'], ['Le sacrum comme base', '18 min', 'Ressentir'], ['Relâcher le psoas', '20 min', 'Préparer'], ['Décompression lombaire', '22 min', 'Préparer'], ['Mobiliser les thoraciques', '25 min', 'Préparer'], ['Cat-Cow conscient', '20 min', 'Préparer'], ['Libérer la nuque', '22 min', 'Préparer'], ['Renforcement profond I', '25 min', 'Exécuter'], ['La planche consciente', '28 min', 'Exécuter'], ['Pont fessier guidé', '28 min', 'Exécuter'], ['Rotation vertébrale', '30 min', 'Exécuter'], ['Extension du dos', '32 min', 'Exécuter'], ['Programme anti-douleur I', '30 min', 'Évoluer'], ['Programme anti-douleur II', '35 min', 'Évoluer'], ['Dos & respiration', '38 min', 'Évoluer'], ['Colonne intégrée', '40 min', 'Évoluer'], ['La colonne parfaite', '45 min', 'Évoluer']],
  p3: [['Comprendre la hanche', '2 min 10 s', 'Comprendre', 'https://vz-1a4e2cac-0dc.b-cdn.net/596e732b-fa75-4606-aa8a-45fb034d2e0b/playlist.m3u8'], ['Le genou fragile', '15 min', 'Comprendre'], ['La cheville oubliée', '12 min', 'Comprendre'], ['Ressentir la hanche', '15 min', 'Ressentir'], ['Cartographie bas du corps', '20 min', 'Ressentir'], ['Mobilisation de hanche I', '20 min', 'Préparer'], ['Libération des fléchisseurs', '22 min', 'Préparer'], ['Mobilisation de hanche II', '25 min', 'Préparer'], ['Mobilité du genou', '20 min', 'Préparer'], ['La cheville en action', '22 min', 'Préparer'], ['Squat conscient I', '25 min', 'Exécuter'], ['Fente guidée', '28 min', 'Exécuter'], ['Pont et rotation de hanche', '28 min', 'Exécuter'], ['Station unipodale', '30 min', 'Exécuter'], ['Circuit mobilité', '32 min', 'Exécuter'], ['Mobilité & Pilates I', '30 min', 'Évoluer'], ['Profondeur de hanche', '35 min', 'Évoluer'], ['Genoux & force', '38 min', 'Évoluer'], ['La chaîne postérieure', '40 min', 'Évoluer'], ['Corps libre en bas', '45 min', 'Évoluer']],
  p4: [['La posture expliquée', '12 min', 'Comprendre'], ['Les 4 courbes naturelles', '15 min', 'Comprendre'], ['Posture & douleur', '15 min', 'Comprendre'], ['Ressentir l\'alignement', '12 min', 'Ressentir'], ['L\'axe vertical', '18 min', 'Ressentir'], ['Débloquer la cage thoracique', '20 min', 'Préparer'], ['Activer les stabilisateurs', '22 min', 'Préparer'], ['Rééquilibrer le bassin', '25 min', 'Préparer'], ['Aligner le cou', '22 min', 'Préparer'], ['Proprioception posturale', '25 min', 'Préparer'], ['Debout conscient', '25 min', 'Exécuter'], ['Marche consciente', '28 min', 'Exécuter'], ['Assis sans souffrir', '25 min', 'Exécuter'], ['Travail en miroir', '30 min', 'Exécuter'], ['Posture sous charge', '32 min', 'Exécuter'], ['Programme bureau I', '25 min', 'Évoluer'], ['Programme bureau II', '30 min', 'Évoluer'], ['Posture & respiration', '35 min', 'Évoluer'], ['Corps en équilibre', '40 min', 'Évoluer'], ['L\'alignement parfait', '45 min', 'Évoluer']],
  p5: [['Comprendre le souffle', '12 min', 'Comprendre'], ['Le diaphragme', '15 min', 'Comprendre'], ['Respiration & nerfs', '15 min', 'Comprendre'], ['Ressentir son souffle', '10 min', 'Ressentir'], ['Le souffle tridimensionnel', '15 min', 'Ressentir'], ['Cohérence cardiaque I', '12 min', 'Préparer'], ['Libérer le diaphragme', '15 min', 'Préparer'], ['Respiration latérale', '18 min', 'Préparer'], ['Respiration dorsale', '20 min', 'Préparer'], ['Plancher pelvien', '22 min', 'Préparer'], ['Pilates breathing I', '20 min', 'Exécuter'], ['Souffle & mouvement', '25 min', 'Exécuter'], ['Cohérence cardiaque II', '20 min', 'Exécuter'], ['Souffle & gainage', '28 min', 'Exécuter'], ['Séquence souffle complet', '30 min', 'Exécuter'], ['Techniques avancées I', '25 min', 'Évoluer'], ['Souffle & performance', '30 min', 'Évoluer'], ['Respiration & émotions', '32 min', 'Évoluer'], ['Anti-stress respiratoire', '35 min', 'Évoluer'], ['Maître du souffle', '40 min', 'Évoluer']],
  p6: [['Qu\'est-ce que la proprioception', '12 min', 'Comprendre'], ['Le corps dans l\'espace', '15 min', 'Comprendre'], ['Conscience & douleur', '15 min', 'Comprendre'], ['Le scan corporel I', '12 min', 'Ressentir'], ['Sentir sans voir', '15 min', 'Ressentir'], ['Équilibre statique I', '15 min', 'Préparer'], ['Micro-mouvements', '18 min', 'Préparer'], ['Équilibre instable', '20 min', 'Préparer'], ['Le regard intérieur', '22 min', 'Préparer'], ['Mapping corporel', '25 min', 'Préparer'], ['Mouvement lent I', '20 min', 'Exécuter'], ['Coordination fine', '25 min', 'Exécuter'], ['Anticipation & réaction', '28 min', 'Exécuter'], ['Mouvement lent II', '30 min', 'Exécuter'], ['Fluidité consciente', '32 min', 'Exécuter'], ['Méditation en mouvement', '25 min', 'Évoluer'], ['Inversion consciente', '30 min', 'Évoluer'], ['Conscience des fascias', '35 min', 'Évoluer'], ['Intelligence corporelle', '38 min', 'Évoluer'], ['L\'être dans le corps', '45 min', 'Évoluer']],
  p7: [['Joseph Pilates & sa méthode', '12 min', 'Comprendre'], ['Les 6 principes du Mat', '15 min', 'Comprendre'], ['Le centre — powerhouse', '15 min', 'Comprendre'], ['Sentir le tapis sous soi', '12 min', 'Ressentir'], ['Connexion bassin-plancher', '15 min', 'Ressentir'], ['Le Hundred — initiation', '20 min', 'Préparer'], ['Roll-Up conscient', '22 min', 'Préparer'], ['Single Leg Circle', '20 min', 'Préparer'], ['Rolling Like a Ball', '18 min', 'Préparer'], ['Activation du centre', '22 min', 'Préparer'], ['La série des 5', '25 min', 'Exécuter'], ['Spine Stretch Forward', '28 min', 'Exécuter'], ['Open Leg Rocker', '30 min', 'Exécuter'], ['Swan & Child', '28 min', 'Exécuter'], ['Side Kick Series', '32 min', 'Exécuter'], ['Séquence Mat niveau 1', '35 min', 'Évoluer'], ['Séquence Mat niveau 2', '38 min', 'Évoluer'], ['Teaser guidé', '40 min', 'Évoluer'], ['Mat flow complet', '42 min', 'Évoluer'], ['Maîtrise du Mat', '45 min', 'Évoluer']],
  p8: [['Pourquoi le bureau fatigue', '5 min', 'Comprendre'], ['Nuque & écrans — le vrai danger', '5 min', 'Comprendre'], ['Assis toute la journée — conséquences', '6 min', 'Comprendre'], ['Ressentir ses tensions assises', '5 min', 'Ressentir'], ['Scan corporel sur chaise', '7 min', 'Ressentir'], ['Étirements nuque assis', '5 min', 'Préparer'], ['Poignets & avant-bras — clavier', '6 min', 'Préparer'], ['Épaules au bureau — relâcher', '7 min', 'Préparer'], ['Dos assis — décompression', '8 min', 'Préparer'], ['Hanches assises — libérer', '7 min', 'Préparer'], ['Respiration anti-stress au bureau', '5 min', 'Exécuter'], ['Rotation thoracique sur chaise', '6 min', 'Exécuter'], ['Micro-pause active — 3 min', '3 min', 'Exécuter'], ['Renforcement postural assis', '8 min', 'Exécuter'], ['Circuit bureau express', '10 min', 'Exécuter'], ['Pause active complète I', '8 min', 'Évoluer'], ['Pause active complète II', '10 min', 'Évoluer'], ['Anti-fatigue écran & nuque', '7 min', 'Évoluer'], ['Routine matin au bureau', '8 min', 'Évoluer'], ['Journée sans douleur — protocole', '10 min', 'Évoluer']],
};

export const SEANCES_EN = {
  p1: [['Understanding the shoulder', '12 min', 'Comprendre'], ['The rotator cuff', '15 min', 'Comprendre'], ['Feeling the shoulder blades', '12 min', 'Ressentir'], ['The weight of the arm', '15 min', 'Ressentir'], ['Awareness circles', '18 min', 'Ressentir'], ['Releasing the trapezius', '20 min', 'Préparer'], ['Mobilizing the scapula', '22 min', 'Préparer'], ['Activating the serratus', '25 min', 'Préparer'], ['Thoracic opening', '28 min', 'Préparer'], ['Shoulder proprioception', '30 min', 'Préparer'], ['The right gesture', '25 min', 'Exécuter'], ['Conscious elevation', '28 min', 'Exécuter'], ['Guided external rotation', '30 min', 'Exécuter'], ['Pulls and pushes', '32 min', 'Exécuter'], ['Full shoulder circuit', '35 min', 'Exécuter'], ['Strength & flexibility I', '35 min', 'Évoluer'], ['Loaded shoulder', '38 min', 'Évoluer'], ['Scapular balance', '40 min', 'Évoluer'], ['The athletic shoulder', '42 min', 'Évoluer'], ['Total mastery', '45 min', 'Évoluer']],
  p2: [['The back explained', '12 min', 'Comprendre'], ['Why the back hurts', '15 min', 'Comprendre'], ['The neck and its tensions', '15 min', 'Comprendre'], ['Feeling the spine', '12 min', 'Ressentir'], ['The sacrum as base', '18 min', 'Ressentir'], ['Releasing the psoas', '20 min', 'Préparer'], ['Lumbar decompression', '22 min', 'Préparer'], ['Mobilizing the thoracics', '25 min', 'Préparer'], ['Conscious Cat-Cow', '20 min', 'Préparer'], ['Releasing the neck', '22 min', 'Préparer'], ['Deep strengthening I', '25 min', 'Exécuter'], ['The conscious plank', '28 min', 'Exécuter'], ['Guided glute bridge', '28 min', 'Exécuter'], ['Vertebral rotation', '30 min', 'Exécuter'], ['Back extension', '32 min', 'Exécuter'], ['Anti-pain program I', '30 min', 'Évoluer'], ['Anti-pain program II', '35 min', 'Évoluer'], ['Back & breathing', '38 min', 'Évoluer'], ['Integrated spine', '40 min', 'Évoluer'], ['The perfect spine', '45 min', 'Évoluer']],
  p3: [['Understanding the hip', '2 min 10 s', 'Comprendre'], ['The fragile knee', '15 min', 'Comprendre'], ['The forgotten ankle', '12 min', 'Comprendre'], ['Feeling the hip', '15 min', 'Ressentir'], ['Lower body mapping', '20 min', 'Ressentir'], ['Hip mobilization I', '20 min', 'Préparer'], ['Releasing the flexors', '22 min', 'Préparer'], ['Hip mobilization II', '25 min', 'Préparer'], ['Knee mobility', '20 min', 'Préparer'], ['The ankle in action', '22 min', 'Préparer'], ['Conscious squat I', '25 min', 'Exécuter'], ['Guided lunge', '28 min', 'Exécuter'], ['Hip bridge & rotation', '28 min', 'Exécuter'], ['Single leg stance', '30 min', 'Exécuter'], ['Mobility circuit', '32 min', 'Exécuter'], ['Mobility & Pilates I', '30 min', 'Évoluer'], ['Hip depth', '35 min', 'Évoluer'], ['Knees & strength', '38 min', 'Évoluer'], ['The posterior chain', '40 min', 'Évoluer'], ['Free lower body', '45 min', 'Évoluer']],
  p4: [['Posture explained', '12 min', 'Comprendre'], ['The 4 natural curves', '15 min', 'Comprendre'], ['Posture & pain', '15 min', 'Comprendre'], ['Feeling alignment', '12 min', 'Ressentir'], ['The vertical axis', '18 min', 'Ressentir'], ['Opening the chest', '20 min', 'Préparer'], ['Activating stabilizers', '22 min', 'Préparer'], ['Rebalancing the pelvis', '25 min', 'Préparer'], ['Aligning the neck', '22 min', 'Préparer'], ['Postural proprioception', '25 min', 'Préparer'], ['Standing consciously', '25 min', 'Exécuter'], ['Conscious walking', '28 min', 'Exécuter'], ['Sitting without pain', '25 min', 'Exécuter'], ['Mirror work', '30 min', 'Exécuter'], ['Posture under load', '32 min', 'Exécuter'], ['Desk program I', '25 min', 'Évoluer'], ['Desk program II', '30 min', 'Évoluer'], ['Posture & breathing', '35 min', 'Évoluer'], ['Body in balance', '40 min', 'Évoluer'], ['Perfect alignment', '45 min', 'Évoluer']],
  p5: [['Understanding the breath', '12 min', 'Comprendre'], ['The diaphragm', '15 min', 'Comprendre'], ['Breathing & nerves', '15 min', 'Comprendre'], ['Feeling your breath', '10 min', 'Ressentir'], ['3D breathing', '15 min', 'Ressentir'], ['Cardiac coherence I', '12 min', 'Préparer'], ['Releasing the diaphragm', '15 min', 'Préparer'], ['Lateral breathing', '18 min', 'Préparer'], ['Dorsal breathing', '20 min', 'Préparer'], ['Pelvic floor', '22 min', 'Préparer'], ['Pilates breathing I', '20 min', 'Exécuter'], ['Breath & movement', '25 min', 'Exécuter'], ['Cardiac coherence II', '20 min', 'Exécuter'], ['Breath & core', '28 min', 'Exécuter'], ['Full breath sequence', '30 min', 'Exécuter'], ['Advanced techniques I', '25 min', 'Évoluer'], ['Breath & performance', '30 min', 'Évoluer'], ['Breathing & emotions', '32 min', 'Évoluer'], ['Anti-stress breathing', '35 min', 'Évoluer'], ['Master of breath', '40 min', 'Évoluer']],
  p6: [['What is proprioception', '12 min', 'Comprendre'], ['The body in space', '15 min', 'Comprendre'], ['Awareness & pain', '15 min', 'Comprendre'], ['Body scan I', '12 min', 'Ressentir'], ['Feeling without seeing', '15 min', 'Ressentir'], ['Static balance I', '15 min', 'Préparer'], ['Micro-movements', '18 min', 'Préparer'], ['Unstable balance', '20 min', 'Préparer'], ['The inner gaze', '22 min', 'Préparer'], ['Body mapping', '25 min', 'Préparer'], ['Slow movement I', '20 min', 'Exécuter'], ['Fine coordination', '25 min', 'Exécuter'], ['Anticipation & reaction', '28 min', 'Exécuter'], ['Slow movement II', '30 min', 'Exécuter'], ['Conscious fluidity', '32 min', 'Exécuter'], ['Movement meditation', '25 min', 'Évoluer'], ['Conscious inversion', '30 min', 'Évoluer'], ['Fascia awareness', '35 min', 'Évoluer'], ['Body intelligence', '38 min', 'Évoluer'], ['Being in the body', '45 min', 'Évoluer']],
  p7: [['Joseph Pilates & his method', '12 min', 'Comprendre'], ['The 6 Mat principles', '15 min', 'Comprendre'], ['The center — powerhouse', '15 min', 'Comprendre'], ['Feeling the mat beneath you', '12 min', 'Ressentir'], ['Pelvis-floor connection', '15 min', 'Ressentir'], ['The Hundred — initiation', '20 min', 'Préparer'], ['Conscious Roll-Up', '22 min', 'Préparer'], ['Single Leg Circle', '20 min', 'Préparer'], ['Rolling Like a Ball', '18 min', 'Préparer'], ['Center activation', '22 min', 'Préparer'], ['The series of 5', '25 min', 'Exécuter'], ['Spine Stretch Forward', '28 min', 'Exécuter'], ['Open Leg Rocker', '30 min', 'Exécuter'], ['Swan & Child', '28 min', 'Exécuter'], ['Side Kick Series', '32 min', 'Exécuter'], ['Mat sequence level 1', '35 min', 'Évoluer'], ['Mat sequence level 2', '38 min', 'Évoluer'], ['Guided Teaser', '40 min', 'Évoluer'], ['Full Mat flow', '42 min', 'Évoluer'], ['Mat mastery', '45 min', 'Évoluer']],
  p8: [['Why the office tires your body', '5 min', 'Comprendre'], ['Neck & screens — the real danger', '5 min', 'Comprendre'], ['Sitting all day — consequences', '6 min', 'Comprendre'], ['Feel your seated tensions', '5 min', 'Ressentir'], ['Body scan on a chair', '7 min', 'Ressentir'], ['Seated neck stretches', '5 min', 'Préparer'], ['Wrists & forearms — keyboard', '6 min', 'Préparer'], ['Shoulders at desk — release', '7 min', 'Préparer'], ['Seated back — decompress', '8 min', 'Préparer'], ['Seated hips — unlock', '7 min', 'Préparer'], ['Anti-stress desk breathing', '5 min', 'Exécuter'], ['Thoracic rotation on chair', '6 min', 'Exécuter'], ['Active micro-break — 3 min', '3 min', 'Exécuter'], ['Seated postural strengthening', '8 min', 'Exécuter'], ['Express desk circuit', '10 min', 'Exécuter'], ['Full active break I', '8 min', 'Évoluer'], ['Full active break II', '10 min', 'Évoluer'], ['Anti-fatigue screen & neck', '7 min', 'Évoluer'], ['Morning office routine', '8 min', 'Évoluer'], ['Pain-free workday — protocol', '10 min', 'Évoluer']],
};

export const PILIERS_BASE = [
  // Ordre = placement autour du cercle (uniforme).
  { key: 'p7', color: 'rgba(255,35,155,1)', bg: 'rgba(255,35,155,0.42)' },
  { key: 'p3', color: 'rgba(0,110,255,1)', bg: 'rgba(0,110,255,0.38)' },
  { key: 'p4', color: 'rgba(245,75,10,1)', bg: 'rgba(245,75,10,0.40)' },
  { key: 'p6', color: 'rgba(185,45,255,1)', bg: 'rgba(185,45,255,0.44)' },
  { key: 'p5', color: 'rgba(55,130,255,1)', bg: 'rgba(55,130,255,0.44)' },
  { key: 'p1', color: 'rgba(0,170,110,1)', bg: 'rgba(0,170,110,0.40)' },
  { key: 'p2', color: 'rgba(255,155,0,1)', bg: 'rgba(255,155,0,0.42)' },
  { key: 'p8', color: 'rgba(0,206,209,1)', bg: 'rgba(0,206,209,0.40)' },
];

export const PILIER_IMAGES = {
  p1: require("../../assets/piliers/epaules.jpg"),
  p2: require("../../assets/piliers/dos.jpg"),
  p3: require("../../assets/piliers/mobilite.jpg"),
  p4: require("../../assets/piliers/posture.jpg"),
  p5: require("../../assets/piliers/eldoa.jpg"),
  p6: require("../../assets/piliers/golf.jpg"),
  p7: require("../../assets/piliers/mat_pilates.jpg"),
  p8: require("../../assets/piliers/office.jpg"),
  sdj: require("../../assets/piliers/seance_du_jour.jpg"),
};
